### ISSUE TITLE
User Story: Auto find audio books copied to my SD card.

### ISSUE THREAD

**Issue by jelkner** [ahirschberg/LibriFox#3]
I want to be able to copy audio books to my SD card from my desktop computer and have LibriFox find them and add them to my list of available books.

== Discussion

The Music app already does this, but it appears to find all files that end in .mp3 extensions, so it finds audio books as well as music.  It might be a good idea to discuss this with the FXOS developers, since I was hoping to put my music in a "Music" directory, and my audio books in an "AudioBooks" directory, and have LibriFox only find the ones in the AudioBooks directory.

**Comment by ahirschberg** [comment]
Could you provide some more information on how you would like this to work?  Currently the files are stored to the path `librifox/id#/ch_index#.mp3` and a reference is stored in JSON.  It would be very annoying (I think) for a user to have to deal with creating book JSON; they would rather just be able to drag and drop, no? I'm thinking that the files downloaded through the app should be in a separate directory from the user added files, and instead of JSON storing the data, LibriFox will just display the file and folder names provided by the user.

**Comment by ahirschberg** [comment]
I've started doing a bit of work on file discovery, I'm thinking that I will store the app's downloads in a `.librifox/` directory and have the user put additional books into the `LibriFox Audiobooks` directory.  This is better for me as the programmer because then I don't have to worry about the user messing with the downloaded books.  However, it might also be more confusing if they find the folder doesn't contain _all_ the books.  Thoughts? 

Also, should I look into parsing the mp3 file ID3 tags, or simply look at the file path for book and chapter title?  It looks like the FXOS music app finds ID3 tags.

**Comment by jelkner** [comment]
I'm on unfamiliar territory here, but my hunch is that, yes, we will want to parse the ID3 tags (which is where the meta-data lives that allows for nice display of information).

**Comment by ahirschberg** [comment]
The latest commit has this working! The bottom four list items there are mp3 files added to the LibriFox Audiobooks folder, which is why they are italicized and have a red border (I'm still working on the styling).  Haven't written tests yet, but everything appears to work as expected.
![loaded_from_filesystem](https://cloud.githubusercontent.com/assets/5578698/8330105/038c7ffc-1a4d-11e5-8eb6-e77351af47b0.png)

Currently I have it set to find all .mp3 and .lfa files present in the LibriFox Audiobooks folder.  Is this what you want? Also, how should I handle the folder creation? If every app creates a folder (or two) things get cluttered fast, and not everyone will use this functionality.  Maybe on first run I should ask the user whether they want the folder to be created?

**Comment by ahirschberg** [comment]
I'm going to close this issue, because the app will display any .lfa formatted mp3 files found in the `LibriFox Audiobooks/` directory.  I will add a popup on first-run where the user can tell the app whether they want the folder created or not.
